"""
Django settings for miweb project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Cargar variables del archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================
# VARIABLES DE ENTORNO
# ============================

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []


# ============================
# APLICACIONES
# ============================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Sites framework (requerido por django-allauth)
    'django.contrib.sites',

    # Django Allauth (registro/social login)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # proveedores sociales opcionales, por ejemplo Google:
    ##'allauth.socialaccount.providers.google',

    # Mis apps
    'tareas',

    # API / REST
    'rest_framework',
    'rest_framework.authtoken',
]

# Site ID requerido por django.contrib.sites
SITE_ID = int(os.getenv('SITE_ID', 1))


# ============================
# MIDDLEWARE
# ============================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # django-allauth necesita AccountMiddleware
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'miweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # necesario para allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'miweb.wsgi.application'


# ============================
# BASE DE DATOS (SQLite por ahora)
# ============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================
# VALIDACIÓN DE CONTRASEÑAS
# ============================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================
# INTERNACIONALIZACIÓN
# ============================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ============================
# ARCHIVOS ESTÁTICOS
# ============================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ============================
# CLAVE PRIMARIA POR DEFECTO
# ============================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================
# AUTENTICACION / DJANGO-ALLAUTH
# ============================

# Backends de autenticación: conservar el backend por defecto y añadir allauth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # backend por defecto
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
]

# Opciones recomendadas para allauth (ajusta según prefieras)
ACCOUNT_AUTHENTICATION_METHOD = os.getenv('ACCOUNT_AUTHENTICATION_METHOD', 'username')  # 'username' | 'email' | 'username_email'
ACCOUNT_EMAIL_VERIFICATION = os.getenv('ACCOUNT_EMAIL_VERIFICATION', 'optional')      # 'mandatory' | 'optional' | 'none'
ACCOUNT_EMAIL_REQUIRED = os.getenv('ACCOUNT_EMAIL_REQUIRED', 'True') == 'True'
LOGIN_REDIRECT_URL = os.getenv('LOGIN_REDIRECT_URL', '/')
ACCOUNT_LOGOUT_REDIRECT_URL = os.getenv('ACCOUNT_LOGOUT_REDIRECT_URL', '/')

# Email backend para desarrollo (cambia en producción)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')


# ============================
# REST FRAMEWORK (DRF)
# ============================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Login normal (navegador)
        'rest_framework.authentication.TokenAuthentication',    # Login por token (API)
    ],
    # Permisos por defecto: lectura pública, escritura solo usuarios autenticados.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ]
}

# Configuración de proveedores sociales (ejemplo básico para Google).
# Completa client_id y secret en el admin -> Social applications y vincula al Site.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        },
    }
}